[package]
name = "rstructures"
version = "0.1.0"
authors = ["Denis Daletski <daletskidenis@gmail.com>"]
edition = "2018"

[lib]
name = "rstructures"
path = "src/lib.rs"

[[bin]]
name = "rstructures"
path = "src/main.rs"

[dependencies]
colored = "1.9.3"
rand = "0.7.3"